<?php
 /* SLIDERS SECTION */
$meta_data = array('name'=>'sliders_tpl');

//A koji sam K. ovo ovde stavio i cemu sluzi????
$options['tabs'][] = array('name'=>__('Sliders', 'kids_theme'), 'id'=>'slider_tab', 'type'=>'tab');

/*$options['sliders']['slider_types'] = array('anything_slider'=>'Anything Slider',
                                            'cycle_slider'   =>'Cycle Slider',
                                            'nivo_slider'    =>'Nivo Slider');*/

$options['sliders']['slider_types'] = array('cycle_slider'   =>'Cycle Slider', 'piece_slider'=>'PieceMaker');

$options['sliders']['incommon'] = array(
                                     'slider_name'=>array('id'=>'slider_name',
                                                         'name'=>__('Slider Name','kids_theme'), 
                            							 'desc'=>__('Slider name description.','kids_theme'),
                                                         'type'=>'text',
                                                         'value' => null,
                                                         'required' => true,
                                                         'default'=>__('Slider Name', 'kids_theme')),
                                     'slider_type'=>array('id'=>'slider_type',
                                                         'name'=>__('Slide Type','kids_theme'), 
            							                 'desc'=>__('Slide type description.','kids_theme'),
                                                         'type'=>'select',
                                                         'required' => true,
                                                         'values' => $options['sliders']['slider_types'],
                                                         'value' => null,
                                                         'default'=>'cycle_slider'),
                                        );

/* Cycle Slider Options */
$options['sliders']['cycle_slider'] =   array('id'=>'cycle_slider', 
			  					            'name'=>'Cycle Slider',
					                        'settings'=>array( // particular settings to this slider	

                                        array(              
                                            'id' => 'has_pagination',              
                                            'name' => __('Show Slider Pagination', 'kids_theme' ),               
                                            'desc' => __(' ', 'kids_theme' ),                              
                                            'type' => 'checkbox',               
                                            'default' => 'on',
                                            'value' => null             
                                        ),
                                        array(				
                                  				'id' => 'autostop',				
                                  				'name' => __('Slide Count', 'kids_theme' ),				
                                  				'desc' => __('True to end slideshow after X transitions (where X == slide count)', 'kids_theme' ),								
                                  				'type' => 'checkbox',				
                                  				'default' => 'off',
                                  			  	'value' => null			
                                      			),	
                                  	    array('id'=>'autostopCount',
                                             'name'=>__('Number of transitions','kids_theme'), 
    							             'desc'=>__('(optionally used with autostop to define X).','kids_theme'),
                                             'type'=>'text',
                                             'value' => null,
                                             'default'=>0),		
                                      			
                                      			
                              			array(				
                              				'id' => 'delay',				
                              				'name' => __('First Delay', 'kids_theme' ),				
                              				'desc' => __('Additional delay (in milliseconds) for first transition (hint: can be negative) ', 'kids_theme' ),								
                              				'type' => 'number',				
                              				'default' => '-4000',
                              				'min'=>'-10000',
                                    		'max' => '10000',
                                    		'step' => '1000',
                              			  	'value' => null				
                              			),	
                              			
                              			array(              
                                            'id' => 'fx',              
                                            'name' => __('Transition effect', 'kids_theme' ),             
                                            'desc' => __('Pick a transition from the list', 'kids_theme' ),                
                                            'type' => 'select',             
                                            'default' => 'fade',               
                                            'values' => array(   
                                                'none' => __('none', 'kids_theme' ),
                              			        'all'  =>__('all', 'kids_theme'),                 
                                                'fade' => __('fade', 'kids_theme' ),
                                                'scrollDown' => __('scrollDown', 'kids_theme' ),
                                                'scrollLeft' => __('scrollLeft', 'kids_theme' ),
                                                'scrollRight' => __('scrollRight', 'kids_theme' ),
                                                'scrollUp' => __('scrollUp', 'kids_theme' ),
                              			        'slideX'  => __('slideX', 'kids_theme' ),
                              			        'slideY'  => __('slideY', 'kids_theme' ),
                              			        'blindX'  => __('blindX', 'kids_theme' ),
                              			        'blindY'  => __('blindY', 'kids_theme' ),
                                                'turnLeft' => __('turnLeft', 'kids_theme' ),
                                                'turnRight' => __('turnRight', 'kids_theme' ),
                                                'turnDown' => __('turnDown', 'kids_theme' ),
                                                'turnUp' => __('turnUp', 'kids_theme' ),
                                                'zoom' => __('zoom', 'kids_theme' ),
                                            ),
                                             'value' => null                
                                        ),
                                        array(              
                                            'id' => 'easing',              
                                            'name' => __('Easing', 'kids_theme' ),             
                                            'desc' => __('Pick a easing type from the list', 'kids_theme' ),                
                                            'type' => 'select',             
                                            'default' => 'jswing',               
                                            'values' => array(   
                                                'jswing' => __('jswing', 'kids_theme'),               
                                                'easeInQuad' => __('easeInQuad', 'kids_theme' ),                 
                                                'easeOutQuad' => __('easeOutQuad', 'kids_theme' ),
                                                'easeInOutQuad' => __('easeInOutQuad', 'kids_theme' ),
                                                'easeInOutCubic' => __('easeInOutCubic', 'kids_theme' ),
                                                'easeInOutQuart' => __('easeInOutQuart', 'kids_theme' ),
                                                'easeInOutQuint' => __('easeInOutQuint', 'kids_theme' ),
                                                'easeInOutSine' => __('easeInOutSine', 'kids_theme' ),
                                                'easeInOutExpo' => __('easeInOutExpo', 'kids_theme' ),
                                                'easeInOutCirc' => __('easeInOutCirc', 'kids_theme' ),
                                                'easeInOutElastic' => __('easeInOutElastic', 'kids_theme' ),
                                                'easeInOutBack' => __('easeInOutBack', 'kids_theme' ),
                                                'easeInBounce' => __('easeInBounce', 'kids_theme' ),
                                                'easeOutBounce' => __('easeOutBounce', 'kids_theme' ),
                                                'easeInOutBounce' => __('easeInOutBounce', 'kids_theme' ),
                                            ),
                                             'value' => null                
                                        ),
                                         array(              
                                            'id' => 'pause',              
                                            'name' => __('Pause slide\'s transitions if mouse over slider.', 'kids_theme' ),               
                                            'desc' => __(' ', 'kids_theme' ),                              
                                            'type' => 'checkbox',               
                                            'default' => 'on',
                                            'value' => null             
                                        ),
                                  		array(				
                                				'id' => 'speed',				
                                				'name' => __('Slide Transition Speed', 'kids_theme' ),				
                                				'desc' => __('Time in milliseconds eg. 5000 = 5 seconds', 'kids_theme' ),				
                                				'type' => 'number',
                                				'min'=>'0',
                                				'max' => '10000',
                                				'step' => '100',
                                				'default' => '1000',
                                			    'value' => null,
                                        		'filters'=>array('intVal')		
                                    			),
                            	  		array(				
                                				'id' => 'timeout',				
                                				'name' => __('Delay beetween slides', 'kids_theme' ),				
                                				'desc' => __('milliseconds between slide transitions (0 to disable auto advance) ', 'kids_theme' ),				
                                				'type' => 'number',
                                				'min'=>'0',
                                				'max' => '10000',
                                				'step' => '100',
                                				'default' => '3000',
                                			  	'value' => null,
                                        		'filters'=>array('intVal')		
                                			),  				
                                        ),
                      						  'item_data'=>array( // One slide sample
                                                     array(
                                                     	 'id'=>'slide_name',
                                                         'name'=>__('Slide Name','kids_theme'), 
                							             'desc'=>__('Slide name description.','kids_theme'),
                                                         'type'=>'text',
                                                         'value' => null,
                                                         'default'=>'Slide title'),
                                                             
                      			                     array(				
                                              				'id' => 'slide_url',				
                                              				'name' => __('Item File', 'kids_theme' ),				
                                              				'desc' => __('Url to the image file for this slide.', 'kids_theme' ),			
                                              				'type' => 'file',				
                                              				'default' => 'http://',
                                                      		'required' => true,
                      			                          'value' => null				
                  			                         ),
                  			                         array(
                                                         	 'id'=>'slide_link',
                                                             'name'=>__('Link','kids_theme'), 
                            							     'desc'=>__('Link slide with particular page on your site or any external link.','kids_theme'),
                                                             'type'=>'text',
                                                             'value'  => null,
                                                             'default'=>'#'
                                                          )
        			                       )
                         );
                         
 
/* Piecemaker Slider */
$options['sliders']['piece_slider'] = array('id'=>'piece_slider', 
			  					            'name'=>'Piecemaker Slider',
					                        'settings'=>array( // particular settings to this slider
                                        
                                                array('id'   =>'LoaderColor',
                                                         'name' => __('Cube Color','kids_theme'), 
                							             'desc' => __('Color of the cubes before the first image appears, also the color of the back sides of the cube, which become visible at some transition types.','kids_theme'),
                                                         'type' => 'colorpicker',
                                                         'value'  => null,
                                                         'default'=> "#333333"),
                                                
                                                array('id'   =>'InnerSideColor',
                                                         'name' => __('Cube inner side Color','kids_theme'), 
                							             'desc' => __('Color of the inner sides of the cube when sliced','kids_theme'),
                                                         'type' => 'colorpicker',
                                                         'value'  => null,
                                                         'default'=> "#222222"),
                                                
                                                 array('id'   =>'SideShadowAlpha',
                                                         'name' =>__('Side darkness','kids_theme'), 
                							             'desc' =>__('"0.8" - Sides get darker when moved away from the front. This is the degree of darkness - 0 == no change, 1 == 100% black.','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min' =>'0',
                                        				 'max' => '1',
                                        				 'step'   => '0.1',
                                                         'value'  => null,
                                                         'default'=> 0.7),
                                                 
                                                 array('id'   =>'DropShadowAlpha',
                                                         'name' =>__('Shadow alpha','kids_theme'), 
                							             'desc' =>__('"0.7" - Alpha of the drop shadow - 0 == no shadow, 1 == opaque.','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min' =>'0',
                                        				 'max' => '1',
                                        				 'step'   => '0.1',
                                                         'value'  => null,
                                                         'default'=> 0.7),
                                                 
                                                 array('id'   =>'DropShadowDistance',
                                                         'name' =>__('Shadow distance','kids_theme'), 
                							             'desc' =>__('"25" - Distance of the shadow from the bottom of the image','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min' =>'0',
                                        				 'max' => '200',
                                        				 'step'   => '1',
                                                         'value'  => null,
                                                         'default'=> 25),
                                                 
                                                 array('id'   =>'DropShadowScale',
                                                         'name' =>__('Shadow scale','kids_theme'), 
                							             'desc' =>__('As the shadow is blurred, it appears wider that the actual image, when not resized. Thus it‘s a good idea to make it slightly smaller. - 1 would be no resizing at all.','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min' =>'0',
                                        				 'max' => '1',
                                        				 'step'   => '0.05',
                                                         'value'  => null,
                                                         'default'=> 0.95),
                                                 
                                                 array('id'   =>'DropShadowBlurX',
                                                         'name' =>__('Blur X','kids_theme'), 
                							             'desc' =>__('Blur of the drop shadow on the x-axis.','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min' =>'0',
                                        				 'max' => '100',
                                        				 'step'   => '1',
                                                         'value'  => null,
                                                         'default'=> 40),
                                                 
                                                 array('id'   =>'DropShadowBlurY',
                                                         'name' =>__('Blur Y','kids_theme'), 
                							             'desc' =>__('Blur of the drop shadow on the y-axis.','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min' =>'0',
                                        				 'max' => '10',
                                        				 'step'   => '1',
                                                         'value'  => null,
                                                         'default'=> 4),
                                                 
                                                 array('id'   =>'MenuDistanceX',
                                                         'name' =>__('Items Distance','kids_theme'), 
                							             'desc' =>__('Distance between two menu items (from center to center).','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min' =>'0',
                                        				 'max' => '50',
                                        				 'step'   => '1',
                                                         'value'  => null,
                                                         'default'=> 20),
                                                 
                                                 array('id' =>'MenuDistanceY',
                                                         'name' =>__('Items Distance','kids_theme'), 
                							             'desc' =>__('Distance of the menu from the bottom of the image.','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min' =>'0',
                                        				 'max' => '45',
                                        				 'step'   => '1',
                                                         'value'  => null,
                                                         'default'=> 40),
                                                 
                                                 array('id' =>'MenuColor1',
                                                         'name' => __('Menu Color 1','kids_theme'), 
                							             'desc' => __('Color of an inactive menu item','kids_theme'),
                                                         'type' => 'colorpicker',
                                                         'value'  => null,
                                                         'default'=> "#999999"),
                                                 
                                                 array('id' =>'MenuColor2',
                                                         'name' => __('Menu Color 2','kids_theme'), 
                							             'desc' => __('Color of an active menu item.','kids_theme'),
                                                         'type' => 'colorpicker',
                                                         'value' => null,
                                                         'default'=> "#333333"),
                                                 
                                                   array('id'   =>'MenuColor3',
                                                         'name' => __('Menu Color 3','kids_theme'), 
                							             'desc' => __('Color of the inner circle of an active menu item. Should equal the background color of the whole thing.','kids_theme'),
                                                         'type' => 'colorpicker',
                                                         'value'  => null,
                                                         'default'=> "#ffffff"),
                                                   
                                                    array('id'   =>'ControlSize',
                                                         'name' => __('Size of the controls','kids_theme'), 
                							             'desc' => __('Size of the controls, which appear on rollover (play, stop, info, link).','kids_theme'),
                                                         'type' => 'number',
                                                         'value'  => null,
                                                     	 'min' =>'20',
                                        				 'max' => '200',
                                        				 'step'   => '1',
                                                         'default'=> 100),
                                                    
                                                    array('id'   =>'ControlDistance',
                                                         'name' => __('Distance between the controls','kids_theme'), 
                							             'desc' => __('Distance between the controls (from the borders).','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min' =>'0',
                                        				 'max' => '100',
                                        				 'step'   => '1',
                                                         'value'  => null,
                                                         'default'=> 20),
                                                    
                                                    array('id'   =>'ControlColor1',
                                                         'name' => __('Control color 1','kids_theme'), 
                							             'desc' => __('Background color of the controls.','kids_theme'),
                                                         'type' => 'colorpicker',
                                                         'value'  => null,
                                                         'default'=> "#222222"),
                                                    
                                                     array('id'   =>'ControlColor2',
                                                         'name' => __('Control color 2','kids_theme'), 
                							             'desc' => __('Font color of the controls','kids_theme'),
                                                         'type' => 'colorpicker',
                                                         'value'  => null,
                                                         'default'=> "#ffffff"),
                                                     
                                                     array('id'   =>'ControlAlpha',
                                                         'name' => __('Control Alpha 1','kids_theme'), 
                							             'desc' => __('Alpha of a control, when mouse is not over.','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min' =>'0',
                                        				 'max' => '1',
                                        				 'step'   => '0.1',
                                                         'value'  => null,
                                                         'default'=> 0.8),
                                                     
                                                     array('id'   =>'ControlAlphaOver',
                                                         'name' => __('Control Alpha Over','kids_theme'), 
                							             'desc' => __('Alpha of a control, when mouse is over.','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min' =>'0',
                                        				 'max' => '1',
                                        				 'step'   => '0.05',
                                                         'value'  => null,
                                                         'default'=> 0.95),
                                                     
                                                     array('id'   =>'ControlsX',
                                                         'name' => __('X-position of the point','kids_theme'), 
                							             'desc' => __('X-position of the point, which aligns the controls (measured from [0,0] of the image).','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min' =>'0',
                                        				 'max' => '900',
                                        				 'step'   => '1',
                                                         'value'  => null,
                                                         'default'=> 450),
                                                     
                                                     array('id'   =>'ControlsY',
                                                         'name' => __('Y-position of the point','kids_theme'), 
                							             'desc' => __('Y-position of the point, which aligns the controls (measured from [0,0] of the image).','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min' =>'0',
                                        				 'max' => '400',
                                        				 'step'   => '1',
                                                         'value'  => null,
                                                         'default'=> 160),
                                                     
                                                     array('id'=>'ControlsAlign',
                                                          'name'=>__('Scroller data source','kids_theme'), 
                            							  'desc'=>__('ype of alignment from the point [controlsX, controlsY] - can be "center", "left" or "right"','kids_theme'),
                                                          'type'=>'radio',
                                                          'default'=>'center',
                                                          'values' =>array('center'=>__('Center','kids_theme'), 'left'=>__('Left','kids_theme'),'right'=>__('Right','kids_theme') ),
                                                          'value' => null
                                                         ),
                                                         
                                                     array('id'=>'Autoplay',
                                                          'name'=>__('Autoplay','kids_theme'), 
                            							  'desc'=>__('Number of seconds from one transition to another, if not stopped. Set to 0 to disable autoplay.','kids_theme'),
                                                          'type'=>'number',
                                                     	  'min' =>'0',
                                        				  'max' => '30',
                                        				  'step'   => '0.5',
                                                          'default'=>10,
                                                          'value' => null
                                                         ),
                                                         
                                                     array('id'=>'FieldOfView',
                                                          'name'=>__('Field Of View','kids_theme'), 
                            							  'desc'=>__('FieldOfView.','kids_theme'),
                                                          'type'=>'number',
                                                     	  'min' =>'1',
                                        				  'max' => '150',
                                        				  'step'   => '1',
                                                          'default'=>45,
                                                          'value' => null
                                                         ),
                                                         
                                                     array('id'=>'TooltipHeight',
                                                          'name'=>__('Tooltip height','kids_theme'), 
                            							  'desc'=>__('Height of the tooltip surface in the menu.','kids_theme'),
                                                          'type'=>'number',
                                                     	  'min' =>'10',
                                        				  'max' => '50',
                                        				  'step'   => '1',
                                                          'default'=>31,
                                                          'value' => null
                                                         ),
                                                         
                                                     array('id'=>'TooltipColor',
                                                          'name'=>__('Tooltip Color','kids_theme'), 
                            							  'desc'=>__('Color of the tooltip surface in the menu.','kids_theme'),
                                                          'type'=>'colorpicker',
                                                          'default'=> '#222222',
                                                          'value' => null
                                                         ),
                                                         
                                                     array('id'=>'TooltipTextY',
                                                          'name'=>__('Tooltip Text Y','kids_theme'), 
                            							  'desc'=>__('Y-distance of the tooltip text field from the top of the tooltip.','kids_theme'),
                                                          'type'=>'number',
                                                     	  'min' =>'0',
                                        				  'max' => '100',
                                        				  'step'   => '1',
                                                          'default'=> 5,
                                                          'value' => null
                                                         ),
                                                         
                                                     array('id'=>'TooltipTextStyle',
                                                          'name'=>__('Tooltip Text Style','kids_theme'), 
                            							  'desc'=>__('Y-distance of the tooltip text field from the top of the tooltip.','kids_theme'),
                                                          'type'=>'text',
                                                          'default'=> 'P-Italic',
                                                          'value' => null
                                                         ),
                                                         
                                                         
                                                     array('id'=>'TooltipTextColor',
                                                          'name'=>__('Tooltip Text Color','kids_theme'), 
                            							  'desc'=>__('Color of the tooltip text.','kids_theme'),
                                                          'type'=>'colorpicker',
                                                          'default'=> '#ffffff',
                                                          'value' => null
                                                         ),  

                                                     array('id'=>'TooltipMarginLeft',
                                                          'name'=>__('Tooltip Margin Left','kids_theme'), 
                            							  'desc'=>__('Margin of the text to the left end of the tooltip.','kids_theme'),
                                                          'type'=>'number',
                                                     	  'min' =>'0',
                                        				  'max' => '20',
                                        				  'step'   => '1',
                                                          'default'=> 5,
                                                          'value' => null
                                                         ),
                                                         
                                                     array('id'=>'TooltipMarginRight',
                                                          'name'=>__('Tooltip Margin Right','kids_theme'), 
                            							  'desc'=>__('Margin of the text to the right end of the tooltip.','kids_theme'),
                                                          'type'=>'number',
                                                     	  'min' =>'0',
                                        				  'max' => '20',
                                        				  'step'   => '1',
                                                          'default'=> 7,
                                                          'value' => null
                                                         ),
                                                         
                                                     array('id'=>'TooltipTextSharpness',
                                                          'name'=>__('Tooltip Text Sharpness','kids_theme'), 
                            							  'desc'=>__('Sharpness of the tooltip text (-400 to 400).','kids_theme'),
                                                          'type'=>'number',
                                                     	  'min' =>'-400',
                                        				  'max' => '400',
                                        				  'step'   => '10',
                                                          'default'=> 0,
                                                          'value' => null
                                                         ),
                                                         
                                                     array('id'=>'TooltipTextThickness',
                                                          'name'=>__('Tooltip Text Thickness','kids_theme'), 
                            							  'desc'=>__('Thickness of the tooltip text (-400 to 400).','kids_theme'),
                                                          'type'=>'number',
                                                     	  'min' =>'-400',
                                        				  'max' => '400',
                                        				  'step'   => '10',
                                                          'default'=> -100,
                                                          'value' => null
                                                         ),
                                                         
                                                     array('id'=>'InfoWidth',
                                                          'name'=>__('Info Width','kids_theme'), 
                            							  'desc'=>__('The width of the info text field.','kids_theme'),
                                                          'type'=>'number',
                                                     	  'min' =>'300',
                                        				  'max' => '900',
                                        				  'step'   => '10',
                                                          'default'=> 400,
                                                          'value' => null
                                                         ),
                                                         
                                                      array('id'=>'InfoBackground',
                                                          'name'=>__('Info Background','kids_theme'), 
                            							  'desc'=>__('The background color of the info text field.','kids_theme'),
                                                          'type'=>'colorpicker',
                                                          'default'=> '#ffffff',
                                                          'value' => null
                                                         ), 
                                                         
                                                      array('id'=>'InfoBackgroundAlpha',
                                                          'name'=>__('Info Background Alpha','kids_theme'), 
                            							  'desc'=>__('The alpha of the background of the info text, the image shines through, when smaller than 1.','kids_theme'),
                                                          'type'=>'number',
                                                     	  'min' =>'0',
                                        				  'max' => '1',
                                        				  'step'   => '0.05',
                                                          'default'=> 0.95,
                                                          'value' => null
                                                         ),
                                                         
                                                     array('id'=>'InfoMargin',
                                                          'name'=>__('Info Margin','kids_theme'), 
                            							  'desc'=>__('The margin of the text field in the info section to all sides.','kids_theme'),
                                                          'type'=>'number',
                                                     	  'min' =>'0',
                                        				  'max' => '30',
                                        				  'step'   => '1',
                                                          'default'=> 15,
                                                          'value' => null
                                                         ),
                                                         
                                                     array('id'=>'InfoSharpness',
                                                          'name'=>__('Info Sharpness','kids_theme'), 
                            							  'desc'=>__('Sharpness of the info text.','kids_theme'),
                                                          'type'=>'number',
                                                     	   'min' =>'-400',
                                        				  'max' => '400',
                                        				  'step'   => '10',
                                                          'default'=> 0,
                                                          'value' => null
                                                         ),
                                                         
                                                     array('id'=>'InfoThickness',
                                                          'name'=>__('Info Thickness','kids_theme'), 
                            							  'desc'=>__('Thickness of the info text.','kids_theme'),
                                                          'type'=>'number',
                                                     	   'min' =>'-400',
                                        				  'max' => '400',
                                        				  'step'   => '10',
                                                          'default'=> 0,
                                                          'value' => null
                                                         )
                                                         
                                                 ),//end of settings
                                                 
                                               'transition' => array(
                                                     array('name'=>__('Transitions','kids_theme'), 
                            							   'id'=>'transition_section', 
                            							   'type'=>'start_sub_section'),
                                                     
                                                     array('id'   =>'Pieces',
                                                         'name' =>__('Number of segments','kids_theme'), 
                							             'desc' =>__('Number of segments in which the image will be sliced.','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min' =>'1',
                                        				 'max' => '30',
                                        				 'step'   => '1',
                                                         'value'  => null,
                                                         'default'=> 9),
                                                     
                                                     array('id'   =>'Time',
                                                         'name' =>__('Time','kids_theme'), 
                							             'desc' =>__('Time for one cube to turn.','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min' =>'0.3',
                                        				 'max' => '3',
                                        				 'step'   => '0.1',
                                                         'value'  => null,
                                                         'default'=> 1.2),
                                                     
                                                     array('id'   =>'Transition',
                                                         'name' =>__('Tween type','kids_theme'), 
                							             'desc' =>__('Type of animation transition.','kids_theme'),
                                                         'type' => 'select',
                                                         'value'  => null,
                                                         'values' => array(
                                                         					"linear"       => 'linear',
                                                         					"easeInSine"   => 'easeInSine',
                                                         					"easeOutSine"   => 'easeOutSine', 
                                                         					"easeInOutSine" => 'easeInOutSine', 
                                                         					"easeInCubic"  => 'easeInCubic', 
                                                         					"easeOutCubic" => 'easeOutCubic', 
                                                         					"easeInOutCubic" => 'easeInOutCubic', 
                                                         					"easeOutInCubic" => 'easeOutInCubic', 
                                                         					"easeInQuint"  => 'easeInQuint', 
                                                         					"easeOutQuint" => 'easeOutQuint', 
                                                         					"easeInOutQuint" => 'easeInOutQuint', 
                                                         					"easeOutInQuint" => 'easeOutInQuint', 
                                                         					"easeInCirc"  => 'easeInCirc', 
                                                         					"easeOutCirc" => 'easeOutCirc', 
                                                         					"easeInOutCirc" => 'easeInOutCirc', 
                                                         					"easeOutInCirc" => 'easeOutInCirc', 
                                                         					"easeInBack"  => 'easeInBack', 
                                                         					"easeOutBack" => 'easeOutBack', 
                                                         					"easeInOutBack" => 'easeInOutBack', 
                                                         					"easeOutInBack" => 'easeOutInBack', 
                                                         					"easeInQuad"  => 'easeInQuad', 
                                                         					"easeOutQuad" => 'easeOutQuad', 
                                                         					"easeInOutQuad" => 'easeInOutQuad', 
                                                         					"easeOutInQuad" => 'easeOutInQuad', 
                                                         					"easeInQuart"  => 'easeInQuart', 
                                                         					"easeOutQuart" => 'easeOutQuart', 
                                                         					"easeInOutQuart" => 'easeInOutQuart', 
                                                         					"easeOutInQuart" => 'easeOutInQuart', 
                                                         					"easeInExpo"  => 'easeInExpo', 
                                                         					"easeOutExpo" => 'easeOutExpo', 
                                                         					"easeInOutExpo" => 'easeInOutExpo', 
                                                         					"easeOutInExpo" => 'easeOutInExpo', 
                                                         					"easeInElastic" => 'easeInElastic', 
                                                         					"easeOutElastic" => 'easeOutElastic', 
                                                         					"easeInOutElastic" => 'easeInOutElastic', 
                                                         					"easeOutInElastic" => 'easeOutInElastic', 
                                                         					"easeInBounce"  => 'easeInBounce', 
                                                         					"easeOutBounce" => 'easeOutBounce', 
                                                         					"easeInOutBounce" => 'easeInOutBounce', 
                                                         					"easeOutInBounce" => 'easeOutInBounce'
                                                                       ), 
                                                         'default'=> 'linear'),
                                                     
                                                     array('id'   =>'Delay',
                                                         'name' =>__('Delay','kids_theme'), 
                							             'desc' =>__('Delay between the start of one cube to the start of the next cube.','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min'  => '0',
                                        				 'max'  => '10',
                                        				 'step'   => '0.1',
                                                         'value'  => null,
                                                         'default'=> 0.1),
                                                     
                                                     array('id'   =>'DepthOffset',
                                                         'name' =>__('DepthOffset','kids_theme'), 
                							             'desc' =>__('The offset during transition on the z-axis. Value between 100 and 1000 are recommended. But go for experiments.','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min'  => '100',
                                        				 'max'  => '1000',
                                        				 'step'   => '50',
                                                         'value'  => null,
                                                         'default'=> 300),
                                                     
                                                     array('id'   =>'CubeDistance', 
                                                         'name' =>__('Cube Distance','kids_theme'), 
                							             'desc' =>__('The distance between the cubes during transition. Values between 0 and 50 are recommended. But go for experiments.','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min'  => '0',
                                        				 'max'  => '50',
                                        				 'step'   => '5',
                                                         'value'  => null,
                                                         'default'=> 30),
                                                   ),
                                                   
                                                  'item_data' => array(
                                                          array(
                                                             'id'=>'slide_type',
                                                             'name'=>__('Slide Type','kids_theme'), 
                            							     'desc'=>__('','kids_theme'),
                                                             'type'=>'radio',
                                                             'value' => null,
                                                             'children' => true,
                                                             'values'=> array('image'=>'Image', 'swf'=>'Flash Clip', 'mp4'=> 'Movie Clip (.mp4)'),
                                                             'default'=>'image'
                                                          ),
                                                           array(
                                                         	 'id'=>'slide_name',
                                                             'name'=>__('Title','kids_theme'), 
                            							     'desc'=>__('Slide\'s title.','kids_theme'),
                                                             'type'=>'text',
                                                             'value' => null,
                                                             'default'=>'Slide title'
                                                          ),
                                                           array(
                                                         	 'id'=>'slide_desc',
                                                             'name'=>__('Description','kids_theme'), 
                            							     'desc'=>__('Slide Description. Allowed HTML tags: p, h1, h2 and a.','kids_theme'),
                                                             'type'=>'textarea',
                                                             'parent_id' => 'slide_type',
                                     						 'depend_id' =>'image',
                                                             'value'  => null,
                                                             'default'=>''
                                                          ),
                                                           array(
                                                         	 'id'=>'slide_link',
                                                             'name'=>__('Link','kids_theme'), 
                            							     'desc'=>__('Link slide with particular page on your site or any external link.','kids_theme'),
                                                             'type'=>'text',
                                                             'parent_id' => 'slide_type',
                                     						 'depend_id' =>'image',
                                                             'value'  => null,
                                                             'default'=>'#'
                                                          ),
                          			                     array(				
                                                  			 'id' => 'slide_url',				
                                                  			 'name' => __('File', 'kids_theme' ),				
                                                  			 'desc' => __('Url to the Image/Video/Flash Movie Clip file for this slide.', 'kids_theme' ),			
                                                  			 'type' => 'file',				
                                                  			 'default' => 'http://',
                                                          	 'required' => true,
                          			                         'value' => null				
                      			                         ),
                      			                          array(				
                                                  			 'id' => 'slide_thumbswfimage',				
                                                  			 'name' => __('Image Preview', 'kids_theme' ),				
                                                  			 'desc' => __('Url to the Preview image of a Flash Clip.', 'kids_theme' ),			
                                                  			 'type' => 'file',	
                      			                             'parent_id' => 'slide_type',
                      			                             'depend_id' => 'swf',		
                                                  			 'default' => 'http://',
                          			                         'value'   => null				
                      			                         ),
                      			                          array(				
                                                  			 'id' => 'slide_thumbmpegimage',				
                                                  			 'name' => __('Image Preview', 'kids_theme' ),				
                                                  			 'desc' => __('Url to the Preview image of a movie clip.', 'kids_theme' ),			
                                                  			 'type' => 'file',	
                      			                             'parent_id' => 'slide_type',
                      			                             'depend_id' => 'mp4',		
                                                  			 'default' => 'http://',
                          			                         'value'   => null				
                      			                         )
                                               )//item data end
                                                //Old settings
                                                  /*  array('id'   =>'segments',
                                                         'name' =>__('Number of segments','kids_theme'), 
                							             'desc' =>__('Number of segments in which the image will be sliced.','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min' =>'1',
                                        				 'max' => '30',
                                        				 'step'   => '1',
                                                         'value'  => null,
                                                         'default'=> 5),
                                                   
                                                   array('id'   =>'tweenTime',
                                                         'name' =>__('Tween Time','kids_theme'), 
                							             'desc' =>__('Number of seconds for each element to be turned.','kids_theme'),
                                                         'type' =>'number',
                                                     	 'min' =>'1',
                                        				 'max' => '30',
                                        				 'step'   => '1',
                                                         'value'  => null,
                                                         'default'=> 3),

                                                   array('id'   =>'tweenDelay',
                                                         'name' =>__('Tween Delay','kids_theme'), 
                							             'desc' =>__('Number of seconds from one element starting to turn to the next element starting.','kids_theme'),
                                                         'type' =>'number',
                                                     	 'min' =>'0.1',
                                        				 'max' => '10',
                                        				 'step'   => '0.1',
                                                         'value'  => null,
                                                         'default'=> '0.1'),	
                                                   
                                                   array('id'   =>'tweenType',
                                                         'name' =>__('Tween type','kids_theme'), 
                							             'desc' =>__('Type of animation transition.','kids_theme'),
                                                         'type' =>'select',
                                                         'value'  => null,
                                                         'values' => array(
                                                         					"linear" => 'linear',
                                                         					"easeInSine" => 'easeInSine',
                                                         					"easeOutSine" => 'easeOutSine', 
                                                         					"easeInOutSine" => 'easeInOutSine', 
                                                         					"easeInCubic" => 'easeInCubic', 
                                                         					"easeOutCubic" => 'easeOutCubic', 
                                                         					"easeInOutCubic" => 'easeInOutCubic', 
                                                         					"easeOutInCubic" => 'easeOutInCubic', 
                                                         					"easeInQuint" => 'easeInQuint', 
                                                         					"easeOutQuint" => 'easeOutQuint', 
                                                         					"easeInOutQuint" => 'easeInOutQuint', 
                                                         					"easeOutInQuint" => 'easeOutInQuint', 
                                                         					"easeInCirc" => 'easeInCirc', 
                                                         					"easeOutCirc" => 'easeOutCirc', 
                                                         					"easeInOutCirc" => 'easeInOutCirc', 
                                                         					"easeOutInCirc" => 'easeOutInCirc', 
                                                         					"easeInBack" => 'easeInBack', 
                                                         					"easeOutBack" => 'easeOutBack', 
                                                         					"easeInOutBack" => 'easeInOutBack', 
                                                         					"easeOutInBack" => 'easeOutInBack', 
                                                         					"easeInQuad" => 'easeInQuad', 
                                                         					"easeOutQuad" => 'easeOutQuad', 
                                                         					"easeInOutQuad" => 'easeInOutQuad', 
                                                         					"easeOutInQuad" => 'easeOutInQuad', 
                                                         					"easeInQuart" => 'easeInQuart', 
                                                         					"easeOutQuart" => 'easeOutQuart', 
                                                         					"easeInOutQuart" => 'easeInOutQuart', 
                                                         					"easeOutInQuart" => 'easeOutInQuart', 
                                                         					"easeInExpo" => 'easeInExpo', 
                                                         					"easeOutExpo" => 'easeOutExpo', 
                                                         					"easeInOutExpo" => 'easeInOutExpo', 
                                                         					"easeOutInExpo" => 'easeOutInExpo', 
                                                         					"easeInElastic" => 'easeInElastic', 
                                                         					"easeOutElastic" => 'easeOutElastic', 
                                                         					"easeInOutElastic" => 'easeInOutElastic', 
                                                         					"easeOutInElastic" => 'easeOutInElastic', 
                                                         					"easeInBounce" => 'easeInBounce', 
                                                         					"easeOutBounce" => 'easeOutBounce', 
                                                         					"easeInOutBounce" => 'easeInOutBounce', 
                                                         					"easeOutInBounce" => 'easeOutInBounce'
                                                                       ), 
                                                         'default'=> 'fade'),	
                                                   
                                                   array('id'   =>'zDistance',
                                                         'name' =>__('Z-Distance','kids_theme'), 
                							             'desc' =>__('to which extend are the cubes moved on z axis when being tweened. Negative values bring the cube closer to the camera, positive values take it further away. A good range is roughly between -200 and 700.','kids_theme'),
                                                         'type' =>'number',
                                                     	 'min' =>'1',
                                        				 'max' => '30',
                                        				 'step'   => '1',
                                                         'value'  => null,
                                                         'default'=> 25),	
                                                   
                                                   array('id'   =>'expand',
                                                         'name' =>__('Expand','kids_theme'), 
                							             'desc' =>__('To which etxend are the cubes moved away from each other when tweening.','kids_theme'),
                                                         'type' =>'text',
                                                         'value'  => null,
                                                         'default'=> 9),

                                                   array('id'   =>'innerColor',
                                                         'name' => __('Inner Color','kids_theme'), 
                							             'desc' => __('Color of the sides of the elements in hex values (e.g. 0x000000 for black).','kids_theme'),
                                                         'type' => 'colorpicker',
                                                         'value'  => null,
                                                         'default'=> "#000000"),
                                                   
                                                   array('id'   =>'textBackground',
                                                         'name' =>__('Text Background','kids_theme'), 
                							             'desc' =>__('Color of the description text background in hex values (e.g. 0xFF0000 for red).','kids_theme'),
                                                         'type' =>'colorpicker',
                                                         'value'  => null,
                                                         'default'=> '#666666'),
                                                   
                                                   array('id'   => 'textDistance',
                                                         'name' => __('Text Distance','kids_theme'), 
                							             'desc' => __('Distance of the info text to the borders of its background.','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min' => '1',
                                        				 'max' => '300',
                                        				 'step'   => '1',
                                                         'value'  => null,
                                                         'default'=> 25),
                                                   
                                                   array('id'   =>'shadowDarknent',
                                                         'name' =>__('Shadow Darknent','kids_theme'), 
                							             'desc' =>__('To which extend are the sides shadowed, when the elements are tweening and the sided move towards the background. 100 is black, 0 is no darkening.','kids_theme'),
                                                         'type' => 'number',
                                                     	 'min' =>'1',
                                        				 'max' => '30',
                                        				 'step'   => '1',
                                                         'value'  => null,
                                                         'default'=> 25),
                                                   
                                                   array('id'      => 'autoplay',
                                                         'name'    => __('Autoplay','kids_theme'), 
                							             'desc'    => __('Number of seconds to the next image when autoplay is on. Set 0, if you don\'t want autoplay.','kids_theme'),
                                                         'type'    => 'number',
                                                    	 'min'     =>'0',
                                        				 'max'     => '30',
                                        				 'step'    => '0.5',
                                                         'default' => '2',
                                                         'value'   => null )                                            
                                                             ),  //settings
                                            'item_data' => array(
                                                          array(
                                                         	 'id'=>'slide_name',
                                                             'name'=>__('Title','kids_theme'), 
                            							     'desc'=>__('Slide Main Title.','kids_theme'),
                                                             'type'=>'text',
                                                             'value' => null,
                                                             'default'=>'Slide title'
                                                          ),
                                                           array(
                                                         	 'id'=>'slide_subtitle',
                                                             'name'=>__('Subtitle','kids_theme'), 
                            							     'desc'=>__('Slide Subtitle.','kids_theme'),
                                                             'type'=>'text',
                                                             'value' => null,
                                                             'default'=>''
                                                          ),
                                                           array(
                                                         	 'id'=>'slide_desc',
                                                             'name'=>__('Description','kids_theme'), 
                            							     'desc'=>__('Slide Description.','kids_theme'),
                                                             'type'=>'textarea',
                                                             'value' => null,
                                                             'default'=>''
                                                          ),
                                                           array(
                                                         	 'id'=>'slide_link',
                                                             'name'=>__('Link','kids_theme'), 
                            							     'desc'=>__('Link slide with particular page on your site or any external link.','kids_theme'),
                                                             'type'=>'text',
                                                             'value' => null,
                                                             'default'=>'#'
                                                          ),
                          			                     array(				
                                                  			 'id' => 'slide_url',				
                                                  			 'name' => __('File', 'kids_theme' ),				
                                                  			 'desc' => __('Url to the Image/Video/Flash Movie Clip file for this slide.', 'kids_theme' ),			
                                                  			 'type' => 'file',				
                                                  			 'default' => 'http://',
                                                          	 'required' => true,
                          			                         'value' => null				
                      			                         )
                                               )//item data end*/
                                                             
                                     );//End of Piece Maker               
                                                             
                                            