<div id="help_tab" class="tab-pane fade in">
	<p><a target="_blank" href="http://www.themelaboratory.com/help/kids/wp/1.3/help.html">Kid's Voice School - WP Theme Documentation (ver1.3)</a></p>
	<p><a target="_blank" href="http://www.themelaboratory.com/help/kids/wp/1.4/help.html">Kid's Voice School - WP Theme Documentation (ver1.4)</a></p>
	<p><a target="_blank" href="http://www.themelaboratory.com/help/kids/wp/1.4.3/help.html">Kid's Voice School - WP Theme Documentation (ver1.4.3)</a></p>
</div> <!-- help_tab -->